// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------------------- //
// differential_manchester_tx //
// -------------------------- //

#define differential_manchester_tx_wrap_target 0
#define differential_manchester_tx_wrap 13
#define differential_manchester_tx_pio_version 0

#define differential_manchester_tx_offset_start 0u

static const uint16_t differential_manchester_tx_program_instructions[] = {
            //     .wrap_target
    0xe028, //  0: set    x, 8
    0x1d41, //  1: jmp    x--, 1          side 1 [5]
    0xe022, //  2: set    x, 2
    0x1743, //  3: jmp    x--, 3          side 0 [7]
    0x6021, //  4: out    x, 1
    0x1e28, //  5: jmp    !x, 8           side 1 [6]
    0xa042, //  6: nop
    0x1604, //  7: jmp    4               side 0 [6]
    0x0709, //  8: jmp    9                      [7]
    0x6021, //  9: out    x, 1
    0x162d, // 10: jmp    !x, 13          side 0 [6]
    0xa042, // 11: nop
    0x1e09, // 12: jmp    9               side 1 [6]
    0x0704, // 13: jmp    4                      [7]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program differential_manchester_tx_program = {
    .instructions = differential_manchester_tx_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = differential_manchester_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config differential_manchester_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + differential_manchester_tx_wrap_target, offset + differential_manchester_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

static inline void differential_manchester_tx_program_init(PIO pio, uint sm, uint offset, uint pin, float div) {
    pio_sm_set_pins_with_mask(pio, sm, 0, 1u << pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    pio_gpio_init(pio, pin);
    pio_sm_config c = differential_manchester_tx_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, pin);
    sm_config_set_out_shift(&c, true, true, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset + differential_manchester_tx_offset_start, &c);
    // Execute a blocking pull so that we maintain the initial line state until data is available
    pio_sm_exec(pio, sm, pio_encode_pull(false, true));
    pio_sm_set_enabled(pio, sm, true);
}

#endif

// -------------------------- //
// differential_manchester_rx //
// -------------------------- //

#define differential_manchester_rx_wrap_target 13
#define differential_manchester_rx_wrap 17
#define differential_manchester_rx_pio_version 0

#define differential_manchester_rx_offset_start 0u

static const uint16_t differential_manchester_rx_program_instructions[] = {
    0x20a0, //  0: wait   1 pin, 0
    0xe03f, //  1: set    x, 31
    0x00c5, //  2: jmp    pin, 5
    0xe021, //  3: set    x, 1
    0x0008, //  4: jmp    8
    0x0042, //  5: jmp    x--, 2
    0xe021, //  6: set    x, 1
    0x0008, //  7: jmp    8
    0x2ba0, //  8: wait   1 pin, 0               [11]
    0x00cc, //  9: jmp    pin, 12
    0x4021, // 10: in     x, 1
    0x0008, // 11: jmp    8
    0x4141, // 12: in     y, 1                   [1]
            //     .wrap_target
    0x2b20, // 13: wait   0 pin, 0               [11]
    0x00d1, // 14: jmp    pin, 17
    0x4041, // 15: in     y, 1
    0x0008, // 16: jmp    8
    0x4121, // 17: in     x, 1                   [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program differential_manchester_rx_program = {
    .instructions = differential_manchester_rx_program_instructions,
    .length = 18,
    .origin = -1,
    .pio_version = differential_manchester_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config differential_manchester_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + differential_manchester_rx_wrap_target, offset + differential_manchester_rx_wrap);
    return c;
}

static inline void differential_manchester_rx_program_init(PIO pio, uint sm, uint offset, uint pin, float div) {
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    pio_gpio_init(pio, pin);
    pio_sm_config c = differential_manchester_rx_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin); // for WAIT
    sm_config_set_jmp_pin(&c, pin); // for JMP
    sm_config_set_in_shift(&c, true, true, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    // X and Y are set to 0 and 1, to conveniently emit these to ISR/FIFO.
    pio_sm_exec(pio, sm, pio_encode_set(pio_x, 1));
    pio_sm_exec(pio, sm, pio_encode_set(pio_y, 0));
    pio_sm_set_enabled(pio, sm, true);
}

#endif

