// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// fsk //
// --- //

#define fsk_wrap_target 0
#define fsk_wrap 6
#define fsk_pio_version 0

static const uint16_t fsk_program_instructions[] = {
            //     .wrap_target
    0xe081, //  0: set    pindirs, 1
    0xe001, //  1: set    pins, 1
    0xa042, //  2: nop
    0xa042, //  3: nop
    0xe000, //  4: set    pins, 0
    0xa042, //  5: nop
    0x0001, //  6: jmp    1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program fsk_program = {
    .instructions = fsk_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = fsk_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config fsk_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + fsk_wrap_target, offset + fsk_wrap);
    return c;
}
#endif

