// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// squarewave //
// ---------- //

#define squarewave_wrap_target 0
#define squarewave_wrap 8
#define squarewave_pio_version 0

static const uint16_t squarewave_program_instructions[] = {
            //     .wrap_target
    0xe083, //  0: set    pindirs, 3
    0xe201, //  1: set    pins, 1                [2]
    0xe002, //  2: set    pins, 2
    0x00c5, //  3: jmp    pin, 5
    0x0001, //  4: jmp    1
    0xe501, //  5: set    pins, 1                [5]
    0xe402, //  6: set    pins, 2                [4]
    0x00c5, //  7: jmp    pin, 5
    0x0001, //  8: jmp    1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program squarewave_program = {
    .instructions = squarewave_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = squarewave_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config squarewave_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + squarewave_wrap_target, offset + squarewave_wrap);
    return c;
}
#endif

